name: OoNiQLah
favicon: null
layout_spectrum: 0.019660949241369963
typography_spectrum: 0.15932969632558525
title: 'OoNiQLah | Digital'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#cecece'
    - '#6f6f6f'
    - '#404040'
  brandStrength: 0.2053332864306867
  lightness: 0.8981884918175638
  saturation: 0.4656721099745482
  rhythmicContrast: 0.39676282624714077
purpose: []
